# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0002_auto_20161014_0157'),
        ('insurances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskTypeAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eav.Attribute')),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurances.RiskType')),
            ],
        ),
        migrations.AlterField(
            model_name='risk',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='risk',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insurances.RiskType'),
            preserve_default=False,
        ),
    ]
